#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SRC_DIR="${SCRIPT_DIR}/src"
GEOCODING_DIR="${SRC_DIR}/geocoding"

echo "comparing Country-State-City JSON files..."
pushd "${GEOCODING_DIR}/datageneration"
node compareCountryStateCityJSONs.js "${GEOCODING_DIR}"
popd
